[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "2.14.1"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.10.7"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/twitchtv/protogen"
  version = "0.1.0"

[prune]
  go-tests = true
  unused-packages = true
