version: 2

defaults: &defaults
    docker:
        - image: quay.io/twirphp/build
          environment:
            CGO_ENABLED: "0"

jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - run:
                name: Install PHP dependencies
                command: composer install
            - run:
                name: Install Go dependencies
                command: go mod download
            - run:
                name: Generate Packr boxes
                command: go generate ./protoc-gen-twirp_php/
            - run:
                name: Test code generator
                command: go test -v ./protoc-gen-twirp_php/...
            - run:
                name: Test shared library
                command: vendor/bin/phpunit -v
            - run:
                name: Generate code
                command: ./gen.sh
            - run:
                name: Test generated code
                command: vendor/bin/phpunit -v --group example
            - run:
                name: Test client compatibility
                command: clientcompat -client clientcompat/compat.sh
            - persist_to_workspace:
                root: .
                paths: .

    release:
        <<: *defaults
        steps:
            - attach_workspace:
                at: /go/src/github.com/twirphp/twirp
            - deploy:
                name: Release to Github
                command: goreleaser --skip-validate

workflows:
    version: 2

    build:
        jobs:
            - build:
                filters:
                    tags:
                        only: /.*/

            - release:
                context: org-global
                requires:
                    - build
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
